In [75]:
import pandas as pd
import json

In [76]:
with open ("../data/raw_data.json","r", encoding = "utf-8") as file:
    raw_data = json.load(file)

In [77]:
raw_data

[{'brands': 'maroc.',
  'categories': 'Beverages and beverages preparations,Beverages,Waters,Spring waters,Mineral waters,Unsweetened beverages,Natural mineral waters',
  'code': '6111035000430',
  'countries': 'Morocco',
  'ingredients_text': 'OBD1 999 999 1112606 266963207 mb',
  'labels': '',
  'nutriments': {'carbohydrates': 42,
   'carbohydrates_100g': 4.2,
   'carbohydrates_serving': 42,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 42,
   'energy': 20,
   'energy-kcal': 0,
   'energy-kcal_100g': 0,
   'energy-kcal_serving': 0,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 0,
   'energy-kcal_value_computed': 168,
   'energy-kj': 20,
   'energy-kj_100g': 2,
   'energy-kj_serving': 20,
   'energy-kj_unit': 'kj',
   'energy-kj_value': 20,
   'energy-kj_value_computed': 714,
   'energy_100g': 2,
   'energy_serving': 20,
   'energy_unit': 'kj',
   'energy_value': 20,
   'fat': 0,
   'fat_100g': 0,
   'fat_serving': 0,
   'fat_unit': 'g',
   'fat_value': 0,
   'fiber': 0,
   'fiber_100g': 0,
   'fiber_serving': 0,
   'fiber_unit': 'g',
   'fiber_value': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'nutrition-score-fr': 1,
   'nutrition-score-fr_100g': 1,
   'proteins': 0,
   'proteins_100g': 0,
   'proteins_serving': 0,
   'proteins_unit': 'g',
   'proteins_value': 0,
   'salt': 0,
   'salt_100g': 0,
   'salt_serving': 0,
   'salt_unit': 'g',
   'salt_value': 0,
   'saturated-fat': 0,
   'saturated-fat_100g': 0,
   'saturated-fat_serving': 0,
   'saturated-fat_unit': 'g',
   'saturated-fat_value': 0,
   'sodium': 0,
   'sodium_100g': 0,
   'sodium_serving': 0,
   'sodium_unit': 'g',
   'sodium_value': 0,
   'sugars': 14,
   'sugars_100g': 1.4,
   'sugars_serving': 14,
   'sugars_unit': 'g',
   'sugars_value': 14},
  'nutrition_grade_fr': 'a',
  'product_name': 'Sidi Ali'},
 {'brands': 'perly',
  'categories': 'Snacks',
  'code': '6111242100992',
  'countries': 'Morocco,United States',
  'ingredients_text': 'جبن طري بالسكر Fromage frais sucré القيمة الغذائية ل 100غ Valeurs nutritionnelles pour 100g القيمة الحرارية ككال 97 Valeurs énergiftiques Kad | Protéines Carbohydrates 9.94 Lipides 9 3,0 è Calcium mg 250 gla البروتينات غ 8.0 9 الكاربوهيدرات الدهنيات الكالسيوم',
  'labels': '',
  'nutriments': {'calcium': 0.25,
   'calcium_100g': 0.25,
   'calcium_label': '0',
   'calcium_serving': 0.25,
   'calcium_unit': 'g',
   'calcium_value': 0.25,
   'carbohydrates': 9.4,
   'carbohydrates_100g': 9.4,
   'carbohydrates_serving': 9.4,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 9.4,
   'energy': 406,
   'energy-kcal': 97,
   'energy-kcal_100g': 97,
   'energy-kcal_serving': 97,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 97,
   'energy-kcal_value_computed': 96.6,
   'energy-kj': 406,
   'energy-kj_100g': 406,
   'energy-kj_serving': 406,
   'energy-kj_unit': 'kJ',
   'energy-kj_value': 406,
   'energy-kj_value_computed': 406.8,
   'energy_100g': 406,
   'energy_serving': 406,
   'energy_unit': 'kJ',
   'energy_value': 406,
   'fat': 3,
   'fat_100g': 3,
   'fat_label': '0',
   'fat_serving': 3,
   'fat_unit': 'g',
   'fat_value': 3,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'proteins': 8,
   'proteins_100g': 8,
   'proteins_serving': 8,
   'proteins_unit': 'g',
   'proteins_value': 8},
  'nutrition_grade_fr': 'unknown',
  'product_name': 'perly'},
 {'brands': 'sidi ali',
  'categories': 'Beverages and beverages preparations,Beverages,Waters,Spring waters,Mineral waters,Natural mineral waters',
  'code': '6111035002175',
  'countries': 'Morocco',
  'ingredients_text': 'Sodium, Calcium, Magnésium, Potassium, Bicarbonates, Sulfates, Chlorures,',
  'labels': 'Green Dot',
  'nova_group': 1,
  'nutriments': {'chloride': 0.014,
   'chloride_100g': 0.014,
   'chloride_unit': 'g',
   'chloride_value': 0.014,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'magnesium': 0.009,
   'magnesium_100g': 0.009,
   'magnesium_unit': 'g',
   'magnesium_value': 0.009,
   'nova-group': 1,
   'nova-group_100g': 1,
   'nova-group_serving': 1,
   'nutrition-score-fr': 0,
   'nutrition-score-fr_100g': 0,
   'potassium': 0.003,
   'potassium_100g': 0.003,
   'potassium_unit': 'g',
   'potassium_value': 0.003,
   'salt': 0.065,
   'salt_100g': 0.065,
   'salt_unit': 'mg',
   'salt_value': 65,
   'sodium': 0.026,
   'sodium_100g': 0.026,
   'sodium_unit': 'mg',
   'sodium_value': 26},
  'nutrition_grade_fr': 'a',
  'product_name': 'Sidi Ali'},
 {'brands': "Les Eaux Minérales d'oulmès,Sidi Ali",
  'categories': 'Beverages and beverages preparations,Beverages,Waters,Spring waters,Mineral waters,Unsweetened beverages,Natural mineral waters',
  'code': '6111035000058',
  'countries': 'Morocco',
  'ingredients_text': '100% mineral water',
  'labels': 'ISO 22000,ISO 14001,ISO 45001,ISO 9001',
  'nova_group': 1,
  'nutriments': {'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'nova-group': 1,
   'nova-group_100g': 1,
   'nova-group_serving': 1,
   'nutrition-score-fr': 0,
   'nutrition-score-fr_100g': 0,
   'salt': 0.065,
   'salt_100g': 0.065,
   'salt_unit': 'mg',
   'salt_value': 65,
   'sodium': 0.026,
   'sodium_100g': 0.026,
   'sodium_unit': 'mg',
   'sodium_value': 26},
  'nutrition_grade_fr': 'a',
  'product_name': 'Eau minérale naturelle'},
 {'brands': 'AQUAFINA',
  'categories': 'Boissons et préparations de boissons,Boissons,Eaux,Eaux de sources,Eaux minérales,Eaux de table',
  'code': '6111252421568',
  'countries': 'المغرب',
  'ingredients_text': 'ouverture et avant le : Voir bouteille. après مياه مصفاة بتقنية اكوافينا هايدرو - 7 Eau purifiée par la technique Aquafina HydRO-7',
  'labels': '',
  'nutriments': {'alcohol': 0,
   'alcohol_100g': 0,
   'alcohol_serving': 0,
   'alcohol_unit': '% vol',
   'alcohol_value': 0,
   'bicarbonate': 0.003,
   'bicarbonate_100g': 0.0003,
   'bicarbonate_serving': 0.003,
   'bicarbonate_unit': 'g',
   'bicarbonate_value': 0.003,
   'calcium': 0.001,
   'calcium_100g': 0.0001,
   'calcium_serving': 0.001,
   'calcium_unit': 'g',
   'calcium_value': 0.001,
   'carbohydrates': 0,
   'carbohydrates_100g': 0,
   'carbohydrates_serving': 0,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 0,
   'energy': 0,
   'energy-kcal': 0,
   'energy-kcal_100g': 0,
   'energy-kcal_serving': 0,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 0,
   'energy-kcal_value_computed': 0,
   'energy-kj': 0,
   'energy-kj_100g': 0,
   'energy-kj_serving': 0,
   'energy-kj_unit': 'kJ',
   'energy-kj_value': 0,
   'energy-kj_value_computed': 0,
   'energy_100g': 0,
   'energy_serving': 0,
   'energy_unit': 'kJ',
   'energy_value': 0,
   'fat': 0,
   'fat_100g': 0,
   'fat_serving': 0,
   'fat_unit': 'g',
   'fat_value': 0,
   'fiber': 0,
   'fiber_100g': 0,
   'fiber_serving': 0,
   'fiber_unit': 'g',
   'fiber_value': 0,
   'fluoride': 0.0005,
   'fluoride_100g': 5e-05,
   'fluoride_serving': 0.0005,
   'fluoride_unit': 'g',
   'fluoride_value': 0.0005,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'iron': 2e-05,
   'iron_100g': 2e-06,
   'iron_serving': 2e-05,
   'iron_unit': 'g',
   'iron_value': 2e-05,
   'magnesium': 0.02,
   'magnesium_100g': 0.002,
   'magnesium_serving': 0.02,
   'magnesium_unit': 'g',
   'magnesium_value': 0.02,
   'nutrition-score-fr': 0,
   'nutrition-score-fr_100g': 0,
   'ph': 7.5,
   'ph_100g': 7.5,
   'ph_modifier': '>',
   'ph_serving': 7.5,
   'ph_unit': 'g',
   'ph_value': 7.5,
   'potassium': 0.001,
   'potassium_100g': 0.0001,
   'potassium_serving': 0.001,
   'potassium_unit': 'g',
   'potassium_value': 0.001,
   'proteins': 0,
   'proteins_100g': 0,
   'proteins_serving': 0,
   'proteins_unit': 'g',
   'proteins_value': 0,
   'salt': 0.00508,
   'salt_100g': 0.000508,
   'salt_serving': 0.00508,
   'salt_unit': 'g',
   'salt_value': 0.00508,
   'saturated-fat': 0,
   'saturated-fat_100g': 0,
   'saturated-fat_serving': 0,
   'saturated-fat_unit': 'g',
   'saturated-fat_value': 0,
   'sodium': 0.002032,
   'sodium_100g': 0.000203,
   'sodium_serving': 0.002032,
   'sodium_unit': 'g',
   'sodium_value': 0.002032,
   'sugars': 0,
   'sugars_100g': 0,
   'sugars_serving': 0,
   'sugars_unit': 'g',
   'sugars_value': 0},
  'nutrition_grade_fr': 'a',
  'product_name': 'اكوافينا'},
 {'brands': 'Jaouda',
  'categories': 'Dairies,Meals,Milks (liquid and powder),Milks,Semi-skimmed milks',
  'code': '6111266962187',
  'countries': 'Morocco',
  'ingredients_text': 'Lait frais pasteurisé demi-écrémé à 15g/l de matière grasse',
  'labels': '',
  'nova_group': 3,
  'nutriments': {'calcium': 0.122,
   'calcium_100g': 0.122,
   'calcium_label': 'Calcium',
   'calcium_unit': 'mg',
   'calcium_value': 122,
   'carbohydrates': 4.9,
   'carbohydrates_100g': 4.9,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 4.9,
   'energy': 188,
   'energy-kcal': 45,
   'energy-kcal_100g': 45,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 45,
   'energy-kcal_value_computed': 45.5,
   'energy-kj': 188,
   'energy-kj_100g': 188,
   'energy-kj_unit': 'kJ',
   'energy-kj_value': 188,
   'energy-kj_value_computed': 191.5,
   'energy_100g': 188,
   'energy_unit': 'kJ',
   'energy_value': 188,
   'fat': 1.5,
   'fat_100g': 1.5,
   'fat_unit': 'g',
   'fat_value': 1.5,
   'fiber_modifier': '-',
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'nova-group': 3,
   'nova-group_100g': 3,
   'nova-group_serving': 3,
   'nutrition-score-fr': -3,
   'nutrition-score-fr_100g': -3,
   'proteins': 3.1,
   'proteins_100g': 3.1,
   'proteins_unit': 'g',
   'proteins_value': 3.1,
   'salt': 0.225,
   'salt_100g': 0.225,
   'salt_unit': 'g',
   'salt_value': 0.225,
   'saturated-fat': 1,
   'saturated-fat_100g': 1,
   'saturated-fat_unit': 'g',
   'saturated-fat_value': 1,
   'sodium': 0.09,
   'sodium_100g': 0.09,
   'sodium_unit': 'g',
   'sodium_value': 0.09,
   'sugars': 0,
   'sugars_100g': 0,
   'sugars_unit': 'g',
   'sugars_value': 0},
  'nutrition_grade_fr': 'b',
  'product_name': 'Lait'},
 {'brands': 'Cristaline',
  'categories': 'Beverages and beverages preparations,Beverages,Waters,Spring waters,Mineral waters,Unsweetened beverages,Natural mineral waters',
  'code': '3274080005003',
  'countries': "Belgium,Côte d'Ivoire,France,Germany,Guadeloupe,Italy,Luxembourg,Mali,Martinique,New Caledonia,Switzerland,United Kingdom",
  'ingredients_text': 'Eau de source',
  'labels': 'Triman,it:acqua-di-sorgente',
  'nova_group': 1,
  'nutriments': {'alpha-linolenic-acid': 0.219,
   'alpha-linolenic-acid_100g': 0.219,
   'alpha-linolenic-acid_serving': 2.19,
   'alpha-linolenic-acid_unit': 'mg',
   'alpha-linolenic-acid_value': 219,
   'arachidic-acid': 0.068,
   'arachidic-acid_100g': 0.068,
   'arachidic-acid_serving': 0.68,
   'arachidic-acid_unit': 'mg',
   'arachidic-acid_value': 68,
   'arachidonic-acid': 0.028,
   'arachidonic-acid_100g': 0.028,
   'arachidonic-acid_serving': 0.28,
   'arachidonic-acid_unit': 'mg',
   'arachidonic-acid_value': 28,
   'behenic-acid': 0.0002,
   'behenic-acid_100g': 0.0002,
   'behenic-acid_serving': 0.002,
   'behenic-acid_unit': 'mg',
   'behenic-acid_value': 0.2,
   'bicarbonate': 0.011,
   'bicarbonate_100g': 0.011,
   'bicarbonate_label': 'Bicarbonate',
   'bicarbonate_serving': 0.11,
   'bicarbonate_unit': 'mg',
   'bicarbonate_value': 11,
   'biotin': 0.002,
   'biotin_100g': 0.002,
   'biotin_serving': 0.02,
   'biotin_unit': 'mg',
   'biotin_value': 2,
   'butyric-acid': 0.012,
   'butyric-acid_100g': 0.012,
   'butyric-acid_serving': 0.12,
   'butyric-acid_unit': 'mg',
   'butyric-acid_value': 12,
   'calcium': 0.068,
   'calcium_100g': 0.068,
   'calcium_label': 'Calcium',
   'calcium_serving': 0.68,
   'calcium_unit': 'mg',
   'calcium_value': 68,
   'carbohydrates': 0,
   'carbohydrates_100g': 0,
   'carbohydrates_serving': 0,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 0,
   'carbon-footprint-from-known-ingredients_product': 600,
   'chloride': 0.028,
   'chloride_100g': 0.028,
   'chloride_label': 'Chlorure',
   'chloride_serving': 0.28,
   'chloride_unit': 'mg',
   'chloride_value': 28,
   'energy': 0,
   'energy-kcal': 0,
   'energy-kcal_100g': 0,
   'energy-kcal_serving': 0,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 0,
   'energy-kcal_value_computed': 0,
   'energy-kj': 0,
   'energy-kj_100g': 0,
   'energy-kj_serving': 0,
   'energy-kj_unit': 'kJ',
   'energy-kj_value': 0,
   'energy-kj_value_computed': 0,
   'energy_100g': 0,
   'energy_serving': 0,
   'energy_unit': 'kJ',
   'energy_value': 0,
   'fat': 0,
   'fat_100g': 0,
   'fat_serving': 0,
   'fat_unit': 'g',
   'fat_value': 0,
   'fiber': 0,
   'fiber_100g': 0,
   'fiber_serving': 0,
   'fiber_unit': 'g',
   'fiber_value': 0,
   'fluoride': 0.0002,
   'fluoride_100g': 0.0002,
   'fluoride_label': 'Fluor',
   'fluoride_serving': 0.002,
   'fluoride_unit': 'mg',
   'fluoride_value': 0.2,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'magnesium': 0.011,
   'magnesium_100g': 0.011,
   'magnesium_label': 'Magnésium',
   'magnesium_serving': 0.11,
   'magnesium_unit': 'mg',
   'magnesium_value': 11,
   'nitrate': 0.001,
   'nitrate_100g': 0.001,
   'nitrate_label': 'Nitrate',
   'nitrate_modifier': '<',
   'nitrate_serving': 0.01,
   'nitrate_unit': 'mg',
   'nitrate_value': 1,
   'nova-group': 1,
   'nova-group_100g': 1,
   'nova-group_serving': 1,
   'nutrition-score-fr': 0,
   'nutrition-score-fr_100g': 0,
   'potassium': 0.002,
   'potassium_100g': 0.002,
   'potassium_label': 'Potassium',
   'potassium_serving': 0.02,
   'potassium_unit': 'mg',
   'potassium_value': 2,
   'proteins': 0,
   'proteins_100g': 0,
   'proteins_serving': 0,
   'proteins_unit': 'g',
   'proteins_value': 0,
   'salt': 0.0525,
   'salt_100g': 0.0525,
   'salt_serving': 0.525,
   'salt_unit': 'mg',
   'salt_value': 52.5,
   'saturated-fat': 0,
   'saturated-fat_100g': 0,
   'saturated-fat_serving': 0,
   'saturated-fat_unit': 'g',
   'saturated-fat_value': 0,
   'silica': 0.012,
   'silica_100g': 0.012,
   'silica_label': 'Silice',
   'silica_serving': 0.12,
   'silica_unit': 'mg',
   'silica_value': 12,
   'sodium': 0.021,
   'sodium_100g': 0.021,
   'sodium_serving': 0.21,
   'sodium_unit': 'mg',
   'sodium_value': 21,
   'sugars': 0,
   'sugars_100g': 0,
   'sugars_serving': 0,
   'sugars_unit': 'g',
   'sugars_value': 0,
   'sulphate': 0.039,
   'sulphate_100g': 0.039,
   'sulphate_label': 'Sulfate',
   'sulphate_serving': 0.39,
   'sulphate_unit': 'mg',
   'sulphate_value': 39},
  'nutrition_grade_fr': 'a',
  'product_name': 'Eau De Source'},
 {'brands': 'MILKY FOOD PROFESSIONAL',
  'categories': 'Dairies,Fermented foods,Fermented milk products,Cheeses,Desserts,Dairy desserts,Fermented dairy desserts,Fromages blancs - petit suisses and skyr,Plain fermented dairy desserts,fr:Fromages blancs,fr:Fromages blancs natures',
  'code': '6111246721261',
  'countries': 'Morocco',
  'ingredients_text': 'Ferments lactiques, Présure, Sel.',
  'labels': '',
  'nova_group': 3,
  'nutriments': {'alcohol': 0,
   'alcohol_100g': 0,
   'alcohol_serving': 0,
   'alcohol_unit': '% vol',
   'alcohol_value': 0,
   'carbohydrates': 6.1,
   'carbohydrates_100g': 6.1,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 6.1,
   'energy': 337,
   'energy-kcal': 80.6,
   'energy-kcal_100g': 80.6,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 80.6,
   'energy-kcal_value_computed': 161.6,
   'energy-kj': 337,
   'energy-kj_100g': 337,
   'energy-kj_unit': 'kJ',
   'energy-kj_value': 337,
   'energy-kj_value_computed': 671.8,
   'energy_100g': 337,
   'energy_unit': 'kJ',
   'energy_value': 337,
   'fat': 12,
   'fat_100g': 12,
   'fat_unit': 'g',
   'fat_value': 12,
   'fiber': 0,
   'fiber_100g': 0,
   'fiber_unit': 'g',
   'fiber_value': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'nova-group': 3,
   'nova-group_100g': 3,
   'nova-group_serving': 3,
   'nutrition-score-fr': -2,
   'nutrition-score-fr_100g': -2,
   'proteins': 7.3,
   'proteins_100g': 7.3,
   'proteins_unit': 'g',
   'proteins_value': 7.3,
   'salt': 0,
   'salt_100g': 0,
   'salt_unit': 'g',
   'salt_value': 0,
   'saturated-fat': 0,
   'saturated-fat_100g': 0,
   'saturated-fat_unit': 'g',
   'saturated-fat_value': 0,
   'sodium': 0,
   'sodium_100g': 0,
   'sodium_unit': 'g',
   'sodium_value': 0,
   'sugars': 0,
   'sugars_100g': 0,
   'sugars_unit': 'g',
   'sugars_value': 0},
  'nutrition_grade_fr': 'a',
  'product_name': 'Fromage blanc nature'},
 {'brands': 'Jaouda',
  'categories': 'Dairies,Milks,Homogenized milks,UHT Milks,Whole milks,Cow milks,Whole milk UHT',
  'code': '6111242101180',
  'countries': 'Democratic Republic of the Congo,Mauritania,Morocco,United States',
  'ingredients_text': 'Lait entier',
  'labels': 'No gluten',
  'nova_group': 1,
  'nutriments': {'alcohol': 0,
   'alcohol_100g': 0,
   'alcohol_serving': 0,
   'alcohol_unit': '% vol',
   'alcohol_value': 0,
   'calcium': 0.12,
   'calcium_100g': 0.12,
   'calcium_label': '0',
   'calcium_serving': 1.08,
   'calcium_unit': 'g',
   'calcium_value': 0.12,
   'carbohydrates': 4.8,
   'carbohydrates_100g': 4.8,
   'carbohydrates_serving': 43.2,
   'carbohydrates_unit': 'g',
   'carbohydrates_value': 4.8,
   'energy': 243,
   'energy-kcal': 58,
   'energy-kcal_100g': 58,
   'energy-kcal_serving': 522,
   'energy-kcal_unit': 'kcal',
   'energy-kcal_value': 58,
   'energy-kcal_value_computed': 58.2,
   'energy_100g': 243,
   'energy_serving': 2190,
   'energy_unit': 'kcal',
   'energy_value': 58,
   'fat': 3,
   'fat_100g': 3,
   'fat_serving': 27,
   'fat_unit': 'g',
   'fat_value': 3,
   'fruits-vegetables-legumes-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-legumes-estimate-from-ingredients_serving': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_100g': 0,
   'fruits-vegetables-nuts-estimate-from-ingredients_serving': 0,
   'nova-group': 1,
   'nova-group_100g': 1,
   'nova-group_serving': 1,
   'nutrition-score-fr': -1,
   'nutrition-score-fr_100g': -1,
   'proteins': 3,
   'proteins_100g': 3,
   'proteins_serving': 27,
   'proteins_unit': 'g',
   'proteins_value': 3,
   'salt': 0,
   'salt_100g': 0,
   'salt_serving': 0,
   'salt_unit': 'g',
   'salt_value': 0,
   'saturated-fat': 0,
   'saturated-fat_100g': 0,
   'saturated-fat_serving': 0,
   'saturated-fat_unit': 'g',

In [78]:
'''loop over each product pop out nutriments 
append product to its new place without nutriments
loop over nutriments to extract key value and add code (product id) to it 
save both to dataframe'''

'loop over each product pop out nutriments \nappend product to its new place without nutriments\nloop over nutriments to extract key value and add code (product id) to it \nsave both to dataframe'

In [79]:
products =[]
nutriments =[]
for product in raw_data:
    nutri =product.pop('nutriments',{})
    products.append(product)
    
    for key,value in nutri.items():
        nutriments.append({'code': product['code'],
                           'nutriments':key,
                           'value':value})

In [80]:
products[:2]

[{'brands': 'maroc.',
  'categories': 'Beverages and beverages preparations,Beverages,Waters,Spring waters,Mineral waters,Unsweetened beverages,Natural mineral waters',
  'code': '6111035000430',
  'countries': 'Morocco',
  'ingredients_text': 'OBD1 999 999 1112606 266963207 mb',
  'labels': '',
  'nutrition_grade_fr': 'a',
  'product_name': 'Sidi Ali'},
 {'brands': 'perly',
  'categories': 'Snacks',
  'code': '6111242100992',
  'countries': 'Morocco,United States',
  'ingredients_text': 'جبن طري بالسكر Fromage frais sucré القيمة الغذائية ل 100غ Valeurs nutritionnelles pour 100g القيمة الحرارية ككال 97 Valeurs énergiftiques Kad | Protéines Carbohydrates 9.94 Lipides 9 3,0 è Calcium mg 250 gla البروتينات غ 8.0 9 الكاربوهيدرات الدهنيات الكالسيوم',
  'labels': '',
  'nutrition_grade_fr': 'unknown',
  'product_name': 'perly'}]

In [81]:
nutriments_df = pd.DataFrame(nutriments)
nutriments_df

                 code             nutriments value
0       6111035000430          carbohydrates    42
1       6111035000430     carbohydrates_100g   4.2
2       6111035000430  carbohydrates_serving    42
3       6111035000430     carbohydrates_unit     g
4       6111035000430    carbohydrates_value    42
...               ...                    ...   ...
674187  4088600134086                 sugars   0.5
674188  4088600134086            sugars_100g   0.5
674189  4088600134086         sugars_serving   0.5
674190  4088600134086            sugars_unit     g
674191  4088600134086           sugars_value   0.5

[674192 rows x 3 columns]

In [82]:
products_df = pd.DataFrame(products)
products_df.head(2)

,brands,categories,code,countries,ingredients_text,labels,nutrition_grade_fr,product_name,nova_group
0,maroc.,"Beverages and beverages preparations,Beverages...",6111035000430,Morocco,OBD1 999 999 1112606 266963207 mb,,a,Sidi Ali,NaN
1,perly,Snacks,6111242100992,"Morocco,United States",جبن طري بالسكر Fromage frais sucré القيمة الغذ...,,unknown,perly,NaN

In [83]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9997 entries, 0 to 9996
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brands              9563 non-null   object
 1   categories          9820 non-null   object
 2   code                9997 non-null   object
 3   countries           9996 non-null   object
 4   ingredients_text    9581 non-null   object
 5   labels              8790 non-null   object
 6   nutrition_grade_fr  9966 non-null   object
 7   product_name        9798 non-null   object
 8   nova_group          8973 non-null   float64
dtypes: float64(1), object(8)
memory usage: 703.0+ KB

In [84]:
products_df.head(
    
)

products_df.tail()

,brands,categories,code,countries,ingredients_text,labels,nutrition_grade_fr,product_name,nova_group
9992,NaN,"Beverages and beverages preparations, Beverage...",6111252420226,"France, en:morocco",NaN,NaN,c,7up,NaN
9993,The Collective,"Beverages, Dairies, Fermented foods, Fermented...",5056138201821,en:gb,"Yoghurt 82% (_milk_) , concentrated apple juic...","No gluten,Vegetarian",d,Suckies peach and apricot,4.0
9994,NaN,"Snacks, Sweet snacks, Confectioneries, en:bisc...",6111255770410,"Senegal, en:morocco","Farine de froment, graisse végétale hydrogénée...",NaN,e,CréXy,4.0
9995,NaN,en:potato-crisps,6111242040984,en:ma,"Pommes de terre, huile végétale (palme), arôme...",NaN,c,Leader Chips,4.0
9996,Worldwide foods,"Plant-based foods and beverages, Plant-based f...",4088600134086,en:United Kingdom,"cooked basmati rice (89%) (water, basmati rice...","Vegetarian, Vegan",c,Special coconut rice,3.0

In [85]:
products_df.columns

Index(['brands', 'categories', 'code', 'countries', 'ingredients_text',
       'labels', 'nutrition_grade_fr', 'product_name', 'nova_group'],
      dtype='object')

In [86]:
products_df['nova_group'] = products_df['nova_group'].fillna(0).astype('Int64')

In [87]:
products_df

,brands,categories,code,countries,ingredients_text,labels,nutrition_grade_fr,product_name,nova_group
0,maroc.,"Beverages and beverages preparations,Beverages...",6111035000430,Morocco,OBD1 999 999 1112606 266963207 mb,,a,Sidi Ali,0
1,perly,Snacks,6111242100992,"Morocco,United States",جبن طري بالسكر Fromage frais sucré القيمة الغذ...,,unknown,perly,0
2,sidi ali,"Beverages and beverages preparations,Beverages...",6111035002175,Morocco,"Sodium, Calcium, Magnésium, Potassium, Bicarbo...",Green Dot,a,Sidi Ali,1
3,"Les Eaux Minérales d'oulmès,Sidi Ali","Beverages and beverages preparations,Beverages...",6111035000058,Morocco,100% mineral water,"ISO 22000,ISO 14001,ISO 45001,ISO 9001",a,Eau minérale naturelle,1
4,AQUAFINA,"Boissons et préparations de boissons,Boissons,...",6111252421568,المغرب,ouverture et avant le : Voir bouteille. après ...,,a,اكوافينا,0
...,...,...,...,...,...,...,...,...,...
9992,NaN,"Beverages and beverages preparations, Beverage...",6111252420226,"France, en:morocco",NaN,NaN,c,7up,0
9993,The Collective,"Beverages, Dairies, Fermented foods, Fermented...",5056138201821,en:gb,"Yoghurt 82% (_milk_) , concentrated apple juic...","No gluten,Vegetarian",d,Suckies peach and apricot,4
9994,NaN,"Snacks, Sweet snacks, Confectioneries, en:bisc...",6111255770410,"Senegal, en:morocco","Farine de froment, graisse végétale hydrogénée...",NaN,e,CréXy,4
9995,NaN,en:potato-crisps,6111242040984,en:ma,"Pommes de terre, huile végétale (palme), arôme...",NaN,c,Leader Chips,4
9996,Worldwide foods,"Plant-based foods and beverages, Plant-based f...",4088600134086,en:United Kingdom,"cooked basmati rice (89%) (water, basmati rice...","Vegetarian, Vegan",c,Special coconut rice,3

In [88]:
nutriments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 674192 entries, 0 to 674191
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   code        674192 non-null  object
 1   nutriments  674192 non-null  object
 2   value       674192 non-null  object
dtypes: object(3)
memory usage: 15.4+ MB

In [89]:
nutriments_df.head(10)

            code             nutriments value
0  6111035000430          carbohydrates    42
1  6111035000430     carbohydrates_100g   4.2
2  6111035000430  carbohydrates_serving    42
3  6111035000430     carbohydrates_unit     g
4  6111035000430    carbohydrates_value    42
5  6111035000430                 energy    20
6  6111035000430            energy-kcal     0
7  6111035000430       energy-kcal_100g     0
8  6111035000430    energy-kcal_serving     0
9  6111035000430       energy-kcal_unit  kcal

In [90]:
strring = "20g"

strring.isalnum()

True

In [91]:
nutriments_df

                 code             nutriments value
0       6111035000430          carbohydrates    42
1       6111035000430     carbohydrates_100g   4.2
2       6111035000430  carbohydrates_serving    42
3       6111035000430     carbohydrates_unit     g
4       6111035000430    carbohydrates_value    42
...               ...                    ...   ...
674187  4088600134086                 sugars   0.5
674188  4088600134086            sugars_100g   0.5
674189  4088600134086         sugars_serving   0.5
674190  4088600134086            sugars_unit     g
674191  4088600134086           sugars_value   0.5

[674192 rows x 3 columns]